// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://almscfhmsqypilbrhqwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsbXNjZmhtc3F5cGlsYnJocXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjI1NTgsImV4cCI6MjA2NjMzODU1OH0.NXf2DqQfb5G31BQT9Li4JpT6ubz5dkHF3k1331rYn6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);